version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - ./target/UserStorageFederation-0.0.1.jar:/opt/keycloak/providers/UserStorageFederation.jar
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: adh6_prod
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
volumes:
  mariadb_data:
