CREATE TABLE IF NOT EXISTS adherents (
    id INT PRIMARY KEY,
    nom VARCHAR(255),
    prenom VARCHAR(255),
    mail VARCHAR(255),
    login VARCHAR(255),
    password VARCHAR(255),
    date_de_depart DATE,
    commentaires TEXT,
    mode_association TINYINT,
    access_token TEXT,
    subnet VARCHAR(255),
    ip VARCHAR(255),
    chambre_id INT,
    created_at DATETIME,
    updated_at DATETIME,
    edminet TINYINT,
    is_naina TINYINT,
    mailinglist TINYINT,
    mail_membership INT,
    ldap_login VARCHAR(255),
    datesignedhosting DATETIME,
    datesignedadhesion DATETIME
);
