name: Update .env on merge

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        run: |
          ./scripts/bump_version.sh
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: bump version via workflow'
          add: '.env pom.xml Makefile docker-compose.dev.yml README.md'
